/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class OffHeapArray {
  /** new OffHeapArray() */
  constructor()
  /** arr.push(value) → returns this for chaining */
  push(value: unknown): this
  /** arr.pop() → last element | undefined */
  pop(): unknown
  /** arr.get(index) → element | undefined */
  get(index: number): unknown
  /** arr.set(index, value)  — throws if index is out of bounds */
  set(index: number, value: unknown): void
  /** arr.length (getter) */
  get length(): number
  /**
   * arr.splice(start, deleteCount, ...items) → removed elements
   *
   * Items are converted before the lock is acquired to avoid holding the lock
   * across JS calls.
   */
  splice(start: number, deleteCount: number, items: Array<unknown>): Array<unknown>
  /**
   * arr.forEach(callback)
   *
   * Live iteration with the same lock-release-per-step semantics as OffHeapMap.
   */
  forEach(callback: (arg0: unknown, arg1: unknown) => unknown): void
}

export declare class OffHeapMap {
  /** new OffHeapMap() */
  constructor()
  /** map.set(key, value) → returns this for chaining */
  set(key: string, value: unknown): this
  /** map.get(key) → OffHeapXxx | primitive | undefined */
  get(key: string): unknown
  /** map.has(key) → boolean */
  has(key: string): boolean
  /** map.delete(key) → boolean */
  delete(key: string): boolean
  /** map.clear() */
  clear(): void
  /** map.size (getter) */
  get size(): number
  /** map.keys() → string[] */
  keys(): Array<string>
  /** map.values() → unknown[] */
  values(): Array<unknown>
  /** map.entries() → [string, unknown][] */
  entries(): [string, unknown][]
  /**
   * map.forEach(callback)
   *
   * Live iteration: releases the lock before each callback invocation so that
   * the callback can safely mutate the same map. Uses positional index (IndexMap)
   * to advance the cursor, consistent with the JS Map.forEach spec for additions
   * and deletions that happen after the current key.
   */
  forEach(callback: (arg0: unknown, arg1: unknown) => unknown): void
}

export declare class OffHeapSet {
  /** new OffHeapSet() */
  constructor()
  /** set.add(value) → returns this for chaining  (primitives only) */
  add(value: unknown): this
  /** set.has(value) → boolean */
  has(value: unknown): boolean
  /** set.delete(value) → boolean */
  delete(value: unknown): boolean
  /** set.clear() */
  clear(): void
  /** set.size (getter) */
  get size(): number
  /** set.values() → primitive[] */
  values(): Array<unknown>
  /**
   * set.forEach(callback)
   *
   * callback receives (value, value) per the JS Set.forEach spec.
   */
  forEach(callback: (arg0: unknown, arg1: unknown) => unknown): void
}
